### ISSUE TITLE
Syntax error in setup.py

### ISSUE THREAD

**Issue by CocoCocoAlx** [chronitis/curseradio#1]
I'm on Debian Jessy here, wIth all libraries up-to-date. When I want to run setup.py, I get this:

➜  curseradio git:(master) ✗ python setup.py                               
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from curseradio import __version__
  File "/home/ivan/curseradio/curseradio/__init__.py", line 6, in <module>
    from .curseradio import OPMLBrowser
  File "/home/ivan/curseradio/curseradio/curseradio.py", line 166
    yield from ()
             ^
SyntaxError: invalid syntax

Do you want to help me? Thanks!

**Comment by chronitis** [comment]
`curseradio` requires python 3. You're getting this error because you're using python 2.7, which does not support the `yield from` syntax. Try `python3 setup.py` instead.

**Comment by CocoCocoAlx** [comment]
Yes, I noticed. Anyway I could't make it work from the source code.
Finally, I get a deb for Ubuntu 14.04 and I was able to install it. Thanks
for the reply. I'm going to close the thread.
